// A23 跨节点 · ERR_A23_* 错误码常量
// 各页面六态机 error/degraded 态统一引用。
export const ERR_A23_INVALID_SCHOOL = 'ERR_A23_INVALID_SCHOOL';
export const ERR_A23_INVALID_CATEGORY = 'ERR_A23_INVALID_CATEGORY';
export const ERR_A23_ENGINE_UNAVAILABLE = 'ERR_A23_ENGINE_UNAVAILABLE';
export const ERR_A23_UNKNOWN_MANSION = 'ERR_A23_UNKNOWN_MANSION';
export const ERR_A23_OUT_OF_RANGE = 'ERR_A23_OUT_OF_RANGE';
export const ERR_A23_INVALID_GROUP = 'ERR_A23_INVALID_GROUP';
export const ERR_A23_PARSE_FAILED = 'ERR_A23_PARSE_FAILED';
