export const tarotCards = [
  // 大阿卡纳 (22张)
  { name: '愚者', type: '大阿卡纳', number: 1 },
  { name: '魔术师', type: '大阿卡纳', number: 2 },
  { name: '女祭司', type: '大阿卡纳', number: 3 },
  { name: '女皇', type: '大阿卡纳', number: 4 },
  { name: '皇帝', type: '大阿卡纳', number: 5 },
  { name: '教皇', type: '大阿卡纳', number: 6 },
  { name: '恋人', type: '大阿卡纳', number: 7 },
  { name: '战车', type: '大阿卡纳', number: 8 },
  { name: '力量', type: '大阿卡纳', number: 9 },
  { name: '隐士', type: '大阿卡纳', number: 10 },
  { name: '命运之轮', type: '大阿卡纳', number: 11 },
  { name: '正义', type: '大阿卡纳', number: 12 },
  { name: '倒吊人', type: '大阿卡纳', number: 13 },
  { name: '死神', type: '大阿卡纳', number: 14 },
  { name: '节制', type: '大阿卡纳', number: 15 },
  { name: '恶魔', type: '大阿卡纳', number: 16 },
  { name: '塔', type: '大阿卡纳', number: 17 },
  { name: '星星', type: '大阿卡纳', number: 18 },
  { name: '月亮', type: '大阿卡纳', number: 19 },
  { name: '太阳', type: '大阿卡纳', number: 20 },
  { name: '审判', type: '大阿卡纳', number: 21 },
  { name: '世界', type: '大阿卡纳', number: 22 },

  // 权杖牌组 (14张)
  { name: '权杖王牌', type: '小阿卡纳', suit: '权杖', number: 23 },
  { name: '权杖二', type: '小阿卡纳', suit: '权杖', number: 24 },
  { name: '权杖三', type: '小阿卡纳', suit: '权杖', number: 25 },
  { name: '权杖四', type: '小阿卡纳', suit: '权杖', number: 26 },
  { name: '权杖五', type: '小阿卡纳', suit: '权杖', number: 27 },
  { name: '权杖六', type: '小阿卡纳', suit: '权杖', number: 28 },
  { name: '权杖七', type: '小阿卡纳', suit: '权杖', number: 29 },
  { name: '权杖八', type: '小阿卡纳', suit: '权杖', number: 30 },
  { name: '权杖九', type: '小阿卡纳', suit: '权杖', number: 31 },
  { name: '权杖十', type: '小阿卡纳', suit: '权杖', number: 32 },
  { name: '权杖侍者', type: '小阿卡纳', suit: '权杖', number: 33 },
  { name: '权杖骑士', type: '小阿卡纳', suit: '权杖', number: 34 },
  { name: '权杖王后', type: '小阿卡纳', suit: '权杖', number: 35 },
  { name: '权杖国王', type: '小阿卡纳', suit: '权杖', number: 36 },

  // 圣杯牌组 (14张)
  { name: '圣杯王牌', type: '小阿卡纳', suit: '圣杯', number: 37 },
  { name: '圣杯二', type: '小阿卡纳', suit: '圣杯', number: 38 },
  { name: '圣杯三', type: '小阿卡纳', suit: '圣杯', number: 39 },
  { name: '圣杯四', type: '小阿卡纳', suit: '圣杯', number: 40 },
  { name: '圣杯五', type: '小阿卡纳', suit: '圣杯', number: 41 },
  { name: '圣杯六', type: '小阿卡纳', suit: '圣杯', number: 42 },
  { name: '圣杯七', type: '小阿卡纳', suit: '圣杯', number: 43 },
  { name: '圣杯八', type: '小阿卡纳', suit: '圣杯', number: 44 },
  { name: '圣杯九', type: '小阿卡纳', suit: '圣杯', number: 45 },
  { name: '圣杯十', type: '小阿卡纳', suit: '圣杯', number: 46 },
  { name: '圣杯侍者', type: '小阿卡纳', suit: '圣杯', number: 47 },
  { name: '圣杯骑士', type: '小阿卡纳', suit: '圣杯', number: 48 },
  { name: '圣杯王后', type: '小阿卡纳', suit: '圣杯', number: 49 },
  { name: '圣杯国王', type: '小阿卡纳', suit: '圣杯', number: 50 },

  // 宝剑牌组 (14张)
  { name: '宝剑王牌', type: '小阿卡纳', suit: '宝剑', number: 51 },
  { name: '宝剑二', type: '小阿卡纳', suit: '宝剑', number: 52 },
  { name: '宝剑三', type: '小阿卡纳', suit: '宝剑', number: 53 },
  { name: '宝剑四', type: '小阿卡纳', suit: '宝剑', number: 54 },
  { name: '宝剑五', type: '小阿卡纳', suit: '宝剑', number: 55 },
  { name: '宝剑六', type: '小阿卡纳', suit: '宝剑', number: 56 },
  { name: '宝剑七', type: '小阿卡纳', suit: '宝剑', number: 57 },
  { name: '宝剑八', type: '小阿卡纳', suit: '宝剑', number: 58 },
  { name: '宝剑九', type: '小阿卡纳', suit: '宝剑', number: 59 },
  { name: '宝剑十', type: '小阿卡纳', suit: '宝剑', number: 60 },
  { name: '宝剑侍者', type: '小阿卡纳', suit: '宝剑', number: 61 },
  { name: '宝剑骑士', type: '小阿卡纳', suit: '宝剑', number: 62 },
  { name: '宝剑王后', type: '小阿卡纳', suit: '宝剑', number: 63 },
  { name: '宝剑国王', type: '小阿卡纳', suit: '宝剑', number: 64 },

  // 钱币牌组 (14张)
  { name: '钱币王牌', type: '小阿卡纳', suit: '钱币', number: 65 },
  { name: '钱币二', type: '小阿卡纳', suit: '钱币', number: 66 },
  { name: '钱币三', type: '小阿卡纳', suit: '钱币', number: 67 },
  { name: '钱币四', type: '小阿卡纳', suit: '钱币', number: 68 },
  { name: '钱币五', type: '小阿卡纳', suit: '钱币', number: 69 },
  { name: '钱币六', type: '小阿卡纳', suit: '钱币', number: 70 },
  { name: '钱币七', type: '小阿卡纳', suit: '钱币', number: 71 },
  { name: '钱币八', type: '小阿卡纳', suit: '钱币', number: 72 },
  { name: '钱币九', type: '小阿卡纳', suit: '钱币', number: 73 },
  { name: '钱币十', type: '小阿卡纳', suit: '钱币', number: 74 },
  { name: '钱币侍者', type: '小阿卡纳', suit: '钱币', number: 75 },
  { name: '钱币骑士', type: '小阿卡纳', suit: '钱币', number: 76 },
  { name: '钱币王后', type: '小阿卡纳', suit: '钱币', number: 77 },
  { name: '钱币国王', type: '小阿卡纳', suit: '钱币', number: 78 },
];

export const tarotSpreads = {
  single: {
    name: '单牌指引',
    description: '以一张牌给出当前问题的核心线索，适合快速聚焦当下状态。',
    positions: ['当前指引'],
    cardCount: 1,
  },
  three: {
    name: '时间流牌阵',
    description: '按过去、现在、未来梳理事件脉络，适合观察趋势推进。',
    positions: ['过去', '现在', '未来'],
    cardCount: 3,
  },
  love: {
    name: '爱情牌阵',
    description: '从双方状态、关系现状、建议与走向观察亲密关系。',
    positions: ['你的内心', '对方的内心', '关系现状', '发展建议', '未来走向'],
    cardCount: 5,
  },
  career: {
    name: '事业牌阵',
    description: '从现状、优势、挑战、机会、行动与结果观察事业议题。',
    positions: ['当前状况', '优势', '挑战', '机会', '行动建议', '结果'],
    cardCount: 6,
  },
  decision: {
    name: '选择牌阵',
    description: '比较两个选择的条件与走向，适合需要权衡取舍的问题。',
    positions: ['现状', '选择A', '选择A结果', '选择B', '选择B结果', '最佳建议'],
    cardCount: 6,
  },
  celtic: {
    name: '凯尔特十字',
    description: '从背景、阻碍、环境、态度与结果多层观察复杂问题。',
    positions: [
      '当前状况',
      '挑战/阻碍',
      '遥远过去',
      '近期过去',
      '可能未来',
      '近期未来',
      '你的态度',
      '外界影响',
      '内心恐惧',
      '最终结果',
    ],
    cardCount: 10,
  },
  chakra: {
    name: '七脉轮牌阵',
    description: '按七个脉轮位置观察身心状态与能量侧重。',
    positions: [
      '海底轮(生存)',
      '脐轮(情感)',
      '太阳轮(意志)',
      '心轮(爱)',
      '喉轮(表达)',
      '眉心轮(直觉)',
      '顶轮(灵性)',
    ],
    cardCount: 7,
  },
  year: {
    name: '年运牌阵',
    description: '按年度阶段与主题位置观察一整年的重点变化。',
    positions: [
      '整体运势',
      '1-3月',
      '4-6月',
      '7-9月',
      '10-12月',
      '爱情',
      '事业',
      '财运',
      '健康',
      '建议',
      '挑战',
      '机遇',
    ],
    cardCount: 12,
  },
  mindBodySpirit: {
    name: '身心灵牌阵',
    description: '检视个人在思想、情感和精神层面的状态，找到内在平衡与和谐。',
    positions: ['心灵/思想', '身体/行动', '精神/灵性'],
    cardCount: 3,
  },
  horseshoe: {
    name: '马蹄铁牌阵',
    description: '对特定问题提供一个全面的概述，涵盖过去、现在、未来、建议和最终结果等七个方面。',
    positions: [
      '过去的影响',
      '现在的状况',
      '未来的发展',
      '给你的建议',
      '环境的影响',
      '你的希望与恐惧',
      '最终的结果',
    ],
    cardCount: 7,
  },
  // ===== 第11轮补交新增 3 键（A11-6 交付，主仓已有 horseshoe/mindBodySpirit/chakra 不再重复） =====
  'holy-triangle': {
    name: '圣三角',
    description: '起因/现状/建议，适合快速定位问题根源。',
    positions: ['起因', '现状', '建议'],
    cardCount: 3,
  },
  relationship: {
    name: '关系牌阵',
    description: '深入剖析双人关系状态、阻碍与走向。',
    positions: ['本人', '对方', '关系现状', '阻碍', '优势', '走向', '建议'],
    cardCount: 7,
  },
  'yes-no': {
    name: '是非牌阵',
    description: '在二元问题中综合有利与不利因素。',
    positions: ['当下', '有利', '不利', '结果倾向', '建议'],
    cardCount: 5,
  },
};
