# -*- coding: utf-8 -*-
"""生成 src/data/terms-7lang.ts（tier1 术语的 7 语言查找表）与键表快照。
数据源：docs/audit/2026-09-13-上线前加固/thread-03-*/output/terms/7lang-terms.csv（1201 行）
产物：
  1. src/data/terms-7lang.ts —— 仅 tier1* 行（filled/partial/supplement），渲染层消费；
     tier2_pending 不入前端包（控体积，与 T4 bundle 治理一致）
  2. docs/audit/2026-09-13-上线前加固/shared/cases/_keys_snapshot.json —— 全量键表快照（T4 规范）
确定性幂等；术语表更新后重跑本脚本 + 提交两者。
"""
import csv
import hashlib
import io
import json
import os
import sys
from datetime import datetime

sys.stdout.reconfigure(encoding='utf-8')
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
CSV = os.path.join(REPO, 'docs', 'audit', '2026-09-13-上线前加固',
                   'thread-03-多语言翻译实现与准确性', 'output', 'terms', '7lang-terms.csv')
OUT_TS = os.path.join(REPO, 'src', 'data', 'terms-7lang.ts')
OUT_SNAPSHOT = os.path.join(REPO, 'docs', 'audit', '2026-09-13-上线前加固',
                            'shared', 'cases', '_keys_snapshot.json')

rows = list(csv.DictReader(io.open(CSV, encoding='utf-8-sig')))
tier1 = [r for r in rows if r['status'].startswith('tier1')]
sha = hashlib.sha256(io.open(CSV, 'rb').read()).hexdigest()

LANG_COLS = [('zh-CN', 'zh'), ('en', 'en'), ('es-ES', 'es'), ('ja', 'ja'),
             ('ko-KR', 'ko'), ('th-TH', 'th'), ('vi-VN', 'vi')]

ts_rows = ',\n  '.join(
    '{ key: %s, pinyin: %s, category: %s, status: %s, i18n: { %s } }' % (
        json.dumps(r['archetype_key'], ensure_ascii=False),
        json.dumps(r['pinyin'], ensure_ascii=False),
        json.dumps(r['category'], ensure_ascii=False),
        json.dumps(r['status'], ensure_ascii=False),
        ', '.join('%s: %s' % (json.dumps(loc), json.dumps(r[col], ensure_ascii=False))
                  for loc, col in LANG_COLS))
    for r in tier1)

TS = '''/**
 * AUTO-GENERATED by scripts/i18n/gen-terms-7lang.py — DO NOT EDIT BY HAND.
 * Source: docs/audit/2026-09-13-上线前加固/thread-03-多语言翻译实现与准确性/output/terms/7lang-terms.csv
 * Snapshot: docs/audit/2026-09-13-上线前加固/shared/cases/_keys_snapshot.json (sha256=%s)
 * Scope: tier1 rows only (filled/partial/supplement)；tier2_pending 不入前端包（体积治理）。
 * 口径：docs/audit/2026-09-13-上线前加固/thread-03-多语言翻译实现与准确性/output/02_准确性口径定义.md
 */
export type TermLocale = 'zh-CN' | 'en' | 'es-ES' | 'ja' | 'ko-KR' | 'th-TH' | 'vi-VN';

export interface TermEntry {
  key: string;
  pinyin: string;
  category: string;
  status: string;
  i18n: Record<TermLocale, string>;
}

export const TERMS_7LANG: TermEntry[] = [
  %s
];

const termByKey = new Map<string, TermEntry>();
const keysByZh = new Map<string, string[]>();
for (const entry of TERMS_7LANG) {
  termByKey.set(entry.key, entry);
  const list = keysByZh.get(entry.i18n['zh-CN']) ?? [];
  list.push(entry.key);
  keysByZh.set(entry.i18n['zh-CN'], list);
}

export function termKeyByZh(zh: string): string | null {
  const keys = keysByZh.get(zh);
  return keys && keys.length === 1 ? keys[0] : null;
}

export function termKeysByZh(zh: string): string[] {
  return keysByZh.get(zh) ?? [];
}

/**
 * 按 archetype_key 或唯一中文源术语翻译；查不到返回 null（调用方按口径显示
 * archetype_key 原文 + 未翻译态，禁止静默 zh 兜底）。
 * 多键命中（如拼音撞车）时传 key 而非 zh。
 */
export function translateTerm(keyOrZh: string, locale: TermLocale): string | null {
  const entry = termByKey.get(keyOrZh);
  if (entry) {
    const value = entry.i18n[locale];
    return value && value !== '—' ? value : null;
  }
  const key = termKeyByZh(keyOrZh);
  if (!key) return null;
  const value = termByKey.get(key)?.i18n[locale];
  return value && value !== '—' ? value : null;
}
''' % (sha[:16], ts_rows)

os.makedirs(os.path.dirname(OUT_TS), exist_ok=True)
io.open(OUT_TS, 'w', encoding='utf-8', newline='\n').write(TS)

snapshot = {
    'generated_at': datetime.now().isoformat(timespec='seconds'),
    'source_csv': os.path.relpath(CSV, REPO).replace('\\\\', '/'),
    'source_csv_sha256': sha,
    'total_keys': len(rows),
    'tier1_keys': len(tier1),
    'keys': [r['archetype_key'] for r in rows],
}
os.makedirs(os.path.dirname(OUT_SNAPSHOT), exist_ok=True)
io.open(OUT_SNAPSHOT, 'w', encoding='utf-8', newline='\n').write(
    json.dumps(snapshot, ensure_ascii=False, indent=1))

print('TS_WRITTEN rows=%d -> %s' % (len(tier1), OUT_TS))
print('SNAPSHOT_WRITTEN keys=%d -> %s' % (len(rows), OUT_SNAPSHOT))
