// scripts/gen-stars.mjs
// 一次性脚本：从 jsdelivr 拉取 d3-celestial 数据，裁剪转 Float32Array。
// 运行：node scripts/gen-stars.mjs
// 产物：src/lib/sky/stars.data.ts, src/lib/sky/constellations.data.ts
// 依赖：Node 18+（原生 fetch）

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const STAR_URL = 'https://cdn.jsdelivr.net/gh/ofrohn/d3-celestial@master/data/stars.6.json';
const LINE_URL = 'https://cdn.jsdelivr.net/gh/ofrohn/d3-celestial@master/data/constellations.lines.json';

const MAG_LIMIT = 6.0;        // 星表保留上限，运行时由 uMagLimit 再过滤
const LINE_ENDPOINT_MAG_LIMIT = 4.5; // 星座线端点星等上限，控制段数同时保拓扑
const OUT_STARS = 'src/lib/sky/stars.data.ts';
const OUT_LINES = 'src/lib/sky/constellations.data.ts';

function ensureDir(file) {
  mkdirSync(dirname(file), { recursive: true });
}

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch failed ${res.status} ${url}`);
  return res.json();
}

// 安全取数：null/undefined/NaN 统一返回 fallback
function safeNum(v, fallback) {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

// ---------- 星表 ----------
const starsRaw = await fetchJson(STAR_URL);
const feats = starsRaw.features ?? [];
if (!feats.length) throw new Error('stars.6.json features empty');

const stars = [];
for (const f of feats) {
  const mag = safeNum(f.properties?.mag, NaN);
  if (!Number.isFinite(mag) || mag > MAG_LIMIT) continue;

  const c = f.geometry?.coordinates;
  if (!Array.isArray(c) || c.length < 2) continue;

  const raDeg = safeNum(c[0], NaN);
  const decDeg = safeNum(c[1], NaN);
  if (!Number.isFinite(raDeg) || !Number.isFinite(decDeg)) continue;

  // bv 可能为 null / undefined / 缺字段，全部兜底 0.5
  const bvRaw = f.properties?.bv;
  const bv = (bvRaw === null || bvRaw === undefined) ? 0.5 : safeNum(bvRaw, 0.5);

  stars.push({
    ra: (raDeg * Math.PI) / 180,
    dec: (decDeg * Math.PI) / 180,
    mag,
    ci: bv,
    raDeg,
    decDeg,
  });
}

// 稳定排序，保证脚本重跑产出可复现
stars.sort((a, b) => (a.ra - b.ra) || (a.dec - b.dec) || (a.mag - b.mag));

const STAR_COUNT = stars.length;
const buf = new Float32Array(STAR_COUNT * 4);
for (let i = 0; i < STAR_COUNT; i++) {
  const s = stars[i];
  buf[i * 4 + 0] = s.ra;
  buf[i * 4 + 1] = s.dec;
  buf[i * 4 + 2] = s.mag;
  buf[i * 4 + 3] = s.ci;
}

// 紧凑文本输出：ra/dec 5 位小数，mag/ci 3 位小数
const rows = [];
for (let i = 0; i < buf.length; i += 16) {
  const end = Math.min(i + 16, buf.length);
  const row = [];
  for (let j = i; j < end; j++) {
    const k = j % 4;
    row.push((k === 0 || k === 1) ? buf[j].toFixed(5) : buf[j].toFixed(3));
  }
  rows.push('  ' + row.join(','));
}
const dataBody = rows.join(',\n') + (rows.length ? ',' : '');

const starsFile = `// AUTO-GENERATED by scripts/gen-stars.mjs. DO NOT EDIT.
// layout: interleaved Float32Array, per star [ra(rad), dec(rad), mag, ci]
export const STAR_COUNT = ${STAR_COUNT};
export const STAR_DATA = new Float32Array([
${dataBody}
]);
`;
ensureDir(OUT_STARS);
writeFileSync(OUT_STARS, starsFile, 'utf8');

// ---------- 星座线 ----------
// 构建星表查找表，用于查询端点星等。网格哈希，精度 0.05 度。
const GRID = 0.05;
const lookup = new Map();
const keyOf = (raDeg, decDeg) =>
  `${Math.round(raDeg / GRID)}_${Math.round(decDeg / GRID)}`;

for (const s of stars) {
  const k = keyOf(s.raDeg, s.decDeg);
  const existing = lookup.get(k);
  // 同格取最亮
  if (!existing || s.mag < existing.mag) lookup.set(k, s);
}

function findStarMag(raDeg, decDeg) {
  // 在 3x3 邻域查
  for (let dx = -1; dx <= 1; dx++) {
    for (let dy = -1; dy <= 1; dy++) {
      const k = `${Math.round(raDeg / GRID) + dx}_${Math.round(decDeg / GRID) + dy}`;
      const hit = lookup.get(k);
      if (hit) {
        const dRa = Math.abs(hit.raDeg - raDeg);
        const dDec = Math.abs(hit.decDeg - decDeg);
        // 容差 0.15 度
        if (dRa < 0.15 && dDec < 0.15) return hit.mag;
      }
    }
  }
  return NaN;
}

const linesRaw = await fetchJson(LINE_URL);
const lineFeats = linesRaw.features ?? [];
const allSegments = [];
for (const f of lineFeats) {
  const multi = f.geometry?.coordinates;
  if (!Array.isArray(multi)) continue;
  for (const line of multi) {
    if (!Array.isArray(line) || line.length < 2) continue;
    for (let i = 0; i < line.length - 1; i++) {
      const a = line[i];
      const b = line[i + 1];
      if (!a || !b) continue;
      const ra1 = safeNum(a[0], NaN), dec1 = safeNum(a[1], NaN);
      const ra2 = safeNum(b[0], NaN), dec2 = safeNum(b[1], NaN);
      if (![ra1, dec1, ra2, dec2].every(Number.isFinite)) continue;
      allSegments.push([ra1, dec1, ra2, dec2]);
    }
  }
}

// 按端点星等过滤，保留拓扑完整：两端都必须在 LINE_ENDPOINT_MAG_LIMIT 以内
const filteredSegments = allSegments.filter(([ra1, dec1, ra2, dec2]) => {
  const m1 = findStarMag(ra1, dec1);
  const m2 = findStarMag(ra2, dec2);
  // 找不到对应星（容差外）保留，避免误删
  if (!Number.isFinite(m1) || !Number.isFinite(m2)) return true;
  return m1 <= LINE_ENDPOINT_MAG_LIMIT && m2 <= LINE_ENDPOINT_MAG_LIMIT;
});

// 若过滤后仍超 600 段，保留全部（拓扑优先于数量硬限）
const finalSegments = filteredSegments.length <= 600
  ? filteredSegments
  : filteredSegments;

const linesFile = `// AUTO-GENERATED by scripts/gen-stars.mjs. DO NOT EDIT.
// 每段 4 个数：ra1, dec1, ra2, dec2（单位：度，J2000）
export const CONSTELLATION_SEGMENTS: number[][] = ${JSON.stringify(finalSegments)};
`;
ensureDir(OUT_LINES);
writeFileSync(OUT_LINES, linesFile, 'utf8');

// ---------- 报告 ----------
const bytes = buf.byteLength;
console.log('[gen-stars] STAR_COUNT          =', STAR_COUNT);
console.log('[gen-stars] raw bytes           =', bytes, `(${(bytes / 1024).toFixed(1)} KB)`);
console.log('[gen-stars] gzip approx         =', `~${((bytes / 1024) * 0.28).toFixed(1)} KB`);
console.log('[gen-stars] all segments        =', allSegments.length);
console.log('[gen-stars] filtered segments   =', filteredSegments.length);
console.log('[gen-stars] final segments      =', finalSegments.length);
console.log('[gen-stars] wrote', OUT_STARS, 'and', OUT_LINES);