/**
 * Build-time SEO prerender for the 280 A-domain content routes.
 *
 * Vite emits one SPA shell. This script copies that shell to each content route
 * and injects route-specific metadata so crawlers and link unfurlers do not see
 * 280 copies of the home-page metadata. The output is deterministic and is
 * regenerated by `pnpm build`; never edit dist/<slug>/index.html by hand.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Paths resolve from the script location, not the process CWD, so calling this
// from another directory cannot silently prerender into the wrong repo.
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, '..');
const DIST = join(ROOT, 'dist');
const SMOKE = join(ROOT, 'build', 'smoke-expectations.json');
const BASE_INDEX = join(DIST, 'index.html');
const SITE = 'https://www.temposoul.com';

const STATIC_DESCRIPTIONS = Object.freeze({
  '/wiki/ten-gods': '系统梳理八字十神的定义、生克关系、性格倾向、组合与喜忌。结合日主强弱阅读，避免把单一十神当作吉凶结论。',
  '/wiki/shen-sha': '汇总天乙贵人、桃花、驿马、华盖、空亡等十二种常见神煞的查法、文化含义与组合阅读边界。',
  '/wiki/four-transform': '理解紫微斗数化禄、化权、化科、化忌与十四主星的组合方式、入宫影响及综合判断顺序。',
  '/wiki/ziwei-patterns': '整理十五种紫微斗数常见格局的成立条件、星曜组合、表现倾向与辨析边界，避免只凭格局名称下结论。',
  '/wiki/palace-star': '从十二宫主题与十四主星特质两个维度阅读一百六十八种宫星组合，并说明三方四正与四化的参考顺序。',
  '/wiki/limit-year-guide': '说明紫微斗数大限、小限、流年的时间层级、起法与四化联动，并给出限年工具的阅读步骤。',
  '/wiki/transits': '介绍西洋占星行运的时间尺度、行星相位与本命盘联动方式，提供由慢到快的分层阅读框架。',
  '/wiki/solar-return': '介绍太阳返照盘的年度主题、返照上升、四轴与宫位阅读框架，并说明与本命盘合参的方法。',
  '/tools/limit-year': '输入基础命盘信息，查询大限、小限与流年三层节律；页面同步解释字段含义、时间范围与阅读边界。',
  '/tools/solar-return': '按出生资料与目标年份生成太阳返照盘，查看返照上升、四轴和重点宫位的年度主题。',
  '/wiki/limit-year-guide/faq': '集中回答大限、小限、流年的区别、时间范围、起限口径与四化阅读顺序等限年工具常见问题。',
  '/wiki/four-transform/pairs': '查询甲乙丙丁戊己庚辛壬癸十天干对应的生年四化配对，并了解禄权科忌的参考边界。',
  '/wiki/palace-star/overview': '总览紫微斗数十二宫位与十四主星的核心主题，快速进入具体宫位与主星组合的解读页面。',
  '/wiki/four-transform/overview': '总览化禄、化权、化科、化忌的核心含义，以及四化与十四主星、十二宫位的阅读关系。',
});

const TEN_GOD_FOCUS = Object.freeze({
  bijian: '自我认同与同辈协作',
  jiecai: '竞争意识与资源分配',
  shishen: '表达创造与生活感受',
  shangguan: '独立表达与规则互动',
  piancai: '机会判断与流动资源',
  zhengcai: '务实经营与稳定资源',
  qisha: '压力应对与行动魄力',
  zhengguan: '责任秩序与职业角色',
  pianyin: '直觉研究与非典型学习',
  zhengyin: '学习支持与安全感',
});

const SHEN_SHA_FOCUS = Object.freeze({
  tianyi: '助力关系与化解倾向',
  wenchang: '学习、文字与表达倾向',
  taohua: '人际吸引与关系边界',
  yima: '迁移、变化与行动节奏',
  huagai: '独处、审美与钻研倾向',
  kongwang: '落空感、转换与取舍课题',
  hongluan: '关系机会与喜庆意象',
  tianxi: '喜事、家庭与庆典意象',
  yangren: '果断、冲劲与冲突管理',
  lushen: '工作收入与生活保障',
  jiangxing: '领导、组织与掌控倾向',
  jinyu: '出行、生活品质与资源意象',
});

const TRANSFORM_FOCUS = Object.freeze({
  lu: '资源增益与机会倾向',
  quan: '推动能力与掌控倾向',
  ke: '表达认可与声誉倾向',
  ji: '阻力课题与调整方向',
});

const PALACE_FOCUS = Object.freeze({
  ming: '个性特质与人生主轴',
  xiongdi: '手足互动与同辈关系',
  fuqi: '伴侣互动与婚恋模式',
  zinv: '亲子关系与创造表达',
  caibo: '财务观念与资源运用',
  jie: '身心倾向与生活提醒',
  qianyi: '外出发展与环境适应',
  jiaoyou: '人际网络与合作模式',
  guanlu: '事业方式与职场特质',
  tianzhai: '家庭观念与居住关系',
  fude: '内在需求与精神状态',
  fumu: '亲缘互动与长辈关系',
});

const CATEGORY_INFO = [
  { prefix: '/wiki/ten-gods/', href: '/wiki/ten-gods', label: '八字十神' },
  { prefix: '/wiki/shen-sha/', href: '/wiki/shen-sha', label: '八字神煞' },
  { prefix: '/wiki/four-transform/', href: '/wiki/four-transform', label: '紫微四化' },
  { prefix: '/wiki/ziwei-patterns/', href: '/wiki/ziwei-patterns', label: '紫微格局' },
  { prefix: '/wiki/palace-star/', href: '/wiki/palace-star', label: '宫位与主星' },
  { prefix: '/wiki/limit-year-guide/', href: '/wiki/limit-year-guide', label: '限年指南' },
  { prefix: '/wiki/limit-year/', href: '/wiki/limit-year-guide', label: '限年指南' },
  { prefix: '/wiki/transits/', href: '/wiki/transits', label: '西占行运' },
  { prefix: '/wiki/solar-return/', href: '/wiki/solar-return', label: '太阳返照' },
];

function fail(msg) {
  console.error(`[prerender-titles] ${msg}`);
  process.exit(1);
}

function escapeHtml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function replaceMetaContent(src, attr, key, content) {
  const tagRe = new RegExp(`<meta\\b(?=[^>]*\\b${attr}="${escapeRegExp(key)}")[^>]*>`, 'i');
  const match = src.match(tagRe);
  const escaped = escapeHtml(content);
  if (!match) {
    return src.replace(/<\/head>/i, `    <meta ${attr}="${key}" content="${escaped}" />\n  </head>`);
  }
  const original = match[0];
  const replacement = /\bcontent="[^"]*"/i.test(original)
    ? original.replace(/\bcontent="[^"]*"/i, `content="${escaped}"`)
    : original.replace(/\s*\/?\s*>$/, ` content="${escaped}" />`);
  return src.replace(tagRe, () => replacement);
}

function replaceCanonical(src, canonical) {
  const tagRe = /<link\b(?=[^>]*\brel="canonical")[^>]*>/i;
  const match = src.match(tagRe);
  const tag = `<link rel="canonical" href="${canonical}" />`;
  if (!match) return src.replace(/<\/head>/i, `    ${tag}\n  </head>`);
  return src.replace(tagRe, tag);
}

function replaceHreflang(src, canonical) {
  const alternateRe = /<link\b(?=[^>]*\brel="alternate")(?=[^>]*\bhreflang="[^"]+")[^>]*>\s*/gi;
  const withoutFalseAlternates = src.replace(alternateRe, '');
  const links = [
    `<link rel="alternate" hreflang="zh-CN" href="${canonical}" />`,
    `<link rel="alternate" hreflang="x-default" href="${canonical}" />`,
  ].join('\n    ');
  return withoutFalseAlternates.replace(
    /(<link\b(?=[^>]*\brel="canonical")[^>]*>)/i,
    `$1\n    ${links}`,
  );
}

function entityFromTitle(title) {
  return title.replace(/详解$/, '').trim();
}

function buildPageSeo(slug, baseTitle) {
  if (STATIC_DESCRIPTIONS[slug]) {
    return {
      title: `${baseTitle}｜命律 TempoSoul`,
      description: STATIC_DESCRIPTIONS[slug],
    };
  }

  let match = slug.match(/^\/wiki\/ten-gods\/([^/]+)$/);
  if (match) {
    const focus = TEN_GOD_FOCUS[match[1]] ?? '性格倾向与十神关系';
    const name = entityFromTitle(baseTitle);
    return {
      title: `${baseTitle}｜${focus}、喜忌与组合 - 命律`,
      description: `${name}在八字十神中如何理解？本文从${focus}、日主强弱、五行喜忌与十神组合展开，帮助综合读盘，不作单一吉凶断言。`,
    };
  }

  match = slug.match(/^\/wiki\/shen-sha\/([^/]+)$/);
  if (match) {
    const focus = SHEN_SHA_FOCUS[match[1]] ?? '命局中的象征倾向';
    const name = entityFromTitle(baseTitle);
    return {
      title: `${baseTitle}｜查法、含义与${focus} - 命律`,
      description: `${name}怎么查、代表什么？本文说明传统查法、${focus}及与五行格局合参的顺序，避免只凭一颗神煞判断吉凶。`,
    };
  }

  match = slug.match(/^\/wiki\/four-transform\/[^/]+-(lu|quan|ke|ji)$/);
  if (match) {
    const focus = TRANSFORM_FOCUS[match[1]] ?? '四化作用';
    const name = entityFromTitle(baseTitle);
    return {
      title: `${baseTitle}｜${focus}：十二宫解读 - 命律`,
      description: `${name}在紫微斗数中侧重${focus}。本文说明其落入十二宫时的表现、与同宫会照星曜的关系及综合阅读顺序。`,
    };
  }

  if (/^\/wiki\/ziwei-patterns\/[^/]+$/.test(slug)) {
    const name = entityFromTitle(baseTitle);
    return {
      title: `${baseTitle}｜成立条件、星曜组合与辨析 - 命律`,
      description: `${name}由哪些星曜与宫位条件构成？本文拆解成立条件、常见表现、四化影响与不成立边界，避免只凭格局名称下结论。`,
    };
  }

  if (/^\/wiki\/limit-year\/[^/]+$/.test(slug)) {
    const name = entityFromTitle(baseTitle);
    return {
      title: `${baseTitle}｜时间范围、起法与四化联动 - 命律`,
      description: `${name}在紫微限年体系中覆盖什么时间范围？本文说明起法、盘面层级、四化联动和与其他时间层的合参方式。`,
    };
  }

  if (slug === '/wiki/transits/detail') {
    return {
      title: `${baseTitle}｜慢行星到快速行星的阅读顺序 - 命律`,
      description: '行运盘如何读？从慢行星背景、快速行星触发、本命相位与容许度四层拆解时间尺度，形成可复用的西占行运阅读顺序。',
    };
  }

  if (slug === '/wiki/solar-return/detail') {
    return {
      title: `${baseTitle}｜年度主题、四轴与重点宫位 - 命律`,
      description: '太阳返照盘如何读？从返照上升、天顶天底、太阳落宫与重点宫位梳理年度主题，并说明与本命盘合参的边界。',
    };
  }

  match = slug.match(/^\/wiki\/palace-star\/([^-]+)-([^/]+)$/);
  if (match) {
    const focus = PALACE_FOCUS[match[1]] ?? '宫位主题与现实表现';
    const name = entityFromTitle(baseTitle);
    return {
      title: `${baseTitle}｜${focus} - 命律`,
      description: `${name}在紫微命盘中如何理解？围绕${focus}，梳理主星特质、优势与压力，以及三方四正和四化的综合判断顺序。`,
    };
  }

  return {
    title: `${baseTitle}｜概念、判断方法与应用边界 - 命律`,
    description: `${baseTitle}的核心概念、判断方法、常见表现与应用边界。结合完整盘面综合理解，不作确定性吉凶断言。`,
  };
}

function buildBreadcrumbs(slug, baseTitle) {
  const items = [{ name: '首页', item: `${SITE}/` }];
  const category = CATEGORY_INFO.find((entry) => slug.startsWith(entry.prefix));
  if (category && category.href !== slug) {
    items.push({ name: category.label, item: `${SITE}${category.href}` });
  }
  items.push({ name: baseTitle, item: `${SITE}${slug}` });
  return items.map((item, index) => ({
    '@type': 'ListItem',
    position: index + 1,
    ...item,
  }));
}

function buildJsonLd(slug, baseTitle, description, canonical) {
  const pageNode = slug.startsWith('/tools/')
    ? {
        '@type': 'WebApplication',
        '@id': `${canonical}#application`,
        name: baseTitle,
        description,
        url: canonical,
        applicationCategory: 'LifestyleApplication',
        operatingSystem: 'Web',
        inLanguage: 'zh-CN',
      }
    : {
        '@type': 'Article',
        '@id': `${canonical}#article`,
        headline: baseTitle,
        description,
        url: canonical,
        mainEntityOfPage: canonical,
        inLanguage: 'zh-CN',
        image: `${SITE}/pwa-512x512.png`,
        isPartOf: { '@id': `${SITE}/#website` },
        author: { '@id': `${SITE}/#organization` },
        publisher: { '@id': `${SITE}/#organization` },
      };

  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': `${SITE}/#organization`,
        name: '命律 TempoSoul',
        url: `${SITE}/`,
      },
      {
        '@type': 'WebSite',
        '@id': `${SITE}/#website`,
        name: '命律 TempoSoul',
        url: `${SITE}/`,
        inLanguage: 'zh-CN',
      },
      pageNode,
      {
        '@type': 'BreadcrumbList',
        '@id': `${canonical}#breadcrumb`,
        itemListElement: buildBreadcrumbs(slug, baseTitle),
      },
    ],
  };
}

function replaceJsonLd(src, jsonLd) {
  const safeJson = JSON.stringify(jsonLd, null, 2).replace(/<\/script/gi, '<\\/script');
  const script = `<script type="application/ld+json" data-prerender-seo>\n${safeJson}\n    </script>`;
  const scriptRe = /<script\b[^>]*type="application\/ld\+json"[^>]*>[\s\S]*?<\/script>/i;
  if (!scriptRe.test(src)) return src.replace(/<\/head>/i, `    ${script}\n  </head>`);
  return src.replace(scriptRe, script);
}

function injectSeo(src, seo, baseTitle, slug) {
  const canonical = `${SITE}${slug}`;
  let out = src;

  out = out.replace(/<title>[^<]*<\/title>/i, `<title>${escapeHtml(seo.title)}</title>`);
  out = replaceMetaContent(out, 'name', 'description', seo.description);
  out = replaceMetaContent(out, 'property', 'og:type', slug.startsWith('/tools/') ? 'website' : 'article');
  out = replaceMetaContent(out, 'property', 'og:locale', 'zh_CN');
  // The static shell lists locale alternates although no locale-specific URLs exist.
  // Remove those false social hints until translated routes have stable, crawlable URLs.
  out = out.replace(
    /<meta\b(?=[^>]*\bproperty="og:locale:alternate")[^>]*>\s*/gi,
    '',
  );
  out = replaceMetaContent(out, 'property', 'og:title', seo.title);
  out = replaceMetaContent(out, 'property', 'og:description', seo.description);
  out = replaceMetaContent(out, 'property', 'og:image', `${SITE}/pwa-512x512.png`);
  out = replaceMetaContent(out, 'property', 'og:url', canonical);
  out = replaceMetaContent(out, 'property', 'og:site_name', '命律 TempoSoul');
  out = replaceMetaContent(out, 'name', 'twitter:card', 'summary_large_image');
  out = replaceMetaContent(out, 'name', 'twitter:title', seo.title);
  out = replaceMetaContent(out, 'name', 'twitter:description', seo.description);
  out = replaceMetaContent(out, 'name', 'twitter:image', `${SITE}/pwa-512x512.png`);
  out = replaceCanonical(out, canonical);
  out = replaceHreflang(out, canonical);
  out = out.replace(
    /\s*<!-- 多语言 hreflang（单 URL SPA，客户端语言切换；x-default 指向默认中文） -->/,
    '\n    <!-- 仅声明可抓取的中文版本；其他语言待拥有独立 URL 后再加入 hreflang。 -->',
  );
  out = out.replace(
    /\s*<!-- 多语言交替 locale（与 hreflang 七语言对齐） -->/,
    '',
  );
  out = replaceJsonLd(out, buildJsonLd(slug, baseTitle, seo.description, canonical));

  // Keep the marker outside the opening tag; the old implementation produced
  // invalid markup (`<body<!-- ... -->`), which could confuse HTML parsers.
  out = out.replace(
    /<body([^>]*)>/i,
    `<body$1>\n    <!-- prerendered:prerender-titles ${slug} -->`,
  );

  return out;
}

if (!existsSync(SMOKE)) fail(`smoke-expectations 不存在：${SMOKE}`);
if (!existsSync(BASE_INDEX)) fail(`dist/index.html 不存在：${BASE_INDEX}（请先 vite build）`);

const smoke = JSON.parse(readFileSync(SMOKE, 'utf8'));
const expectations = smoke.expectations;
if (!Array.isArray(expectations) || expectations.length === 0) {
  fail('smoke.expectations 不是非空数组');
}
const total = smoke.total ?? expectations.length;
if (expectations.length !== total) {
  fail(`expectations 数量 ${expectations.length} 与 total ${total} 不一致`);
}

const baseHtml = readFileSync(BASE_INDEX, 'utf8');
const seenSlugs = new Set();
const seenTitles = new Set();
const seenDescriptions = new Set();
let written = 0;

for (const entry of expectations) {
  const { slug, title: baseTitle } = entry;
  if (typeof slug !== 'string' || typeof baseTitle !== 'string') {
    fail('expectation 存在非法 slug/title');
  }
  if (!/^\/(?:[a-z0-9_-]+\/?)+$/.test(slug)) fail(`非法 slug：${slug}`);
  if (seenSlugs.has(slug)) fail(`重复 slug：${slug}`);
  seenSlugs.add(slug);

  const seo = buildPageSeo(slug, baseTitle);
  if (seenTitles.has(seo.title)) fail(`重复 SEO title：${seo.title}`);
  if (seenDescriptions.has(seo.description)) fail(`重复 SEO description：${seo.description}`);
  seenTitles.add(seo.title);
  seenDescriptions.add(seo.description);

  const rel = slug.replace(/^\/+/, '');
  const outDir = join(DIST, rel);
  const outFile = join(outDir, 'index.html');
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, injectSeo(baseHtml, seo, baseTitle, slug), 'utf8');

  // Guard for the `<body<!-- ... -->` regression (see injectSeo). The markup is
  // produced deterministically by this file, so a broken <body> is a code
  // regression rather than content drift. Check the bytes actually written and
  // fail per slug so the culprit is named.
  if (readFileSync(outFile, 'utf8').includes('<body<!--')) {
    fail(`${slug}: 生成了非法 body 起始标签 <body<!--（prerender-titles 注入回归）`);
  }
  written += 1;
}

console.log(`[prerender-titles] 注入 ${written} / ${total} 个 slug`);
console.log(`[prerender-titles] 唯一 title=${seenTitles.size}，唯一 description=${seenDescriptions.size}`);
if (written !== total) fail(`注入数量 ${written} 与期望 ${total} 不一致`);
console.log('[prerender-titles] 完成：title/description/canonical/social/hreflang/JSON-LD 已就绪。');
