// AUTO-GENERATED by T-15C (scratch_t15c). swisseph gold longitudes, Moshier, swe.deltat.
// scope -> body -> ecliptic longitude deg. Do not hand-edit; regenerate from gold fixtures.
export const GOLD_SWISSEPH: Record<string, Record<string, number>> = {
  'sample-1900-beijing': { Sun: 294.59155, Moon: 107.514684, Mercury: 278.871453, Venus: 323.946133, Mars: 294.839383, Jupiter: 243.779711, Saturn: 269.32848, Uranus: 250.877541, Neptune: 84.854685, Pluto: 75.02606 },
  'sample-1990-shanghai': { Sun: 58.912228, Moon: 358.80531, Mercury: 38.284211, Venus: 18.182151, Mars: 351.810514, Jupiter: 100.44179, Saturn: 295.152866, Uranus: 279.061476, Neptune: 284.278974, Pluto: 226.038502 },
  'sample-1950-newyork': { Sun: 112.622187, Moon: 118.467991, Mercury: 117.918996, Venus: 81.601058, Mars: 195.326787, Jupiter: 336.893025, Saturn: 165.5946, Uranus: 96.280746, Neptune: 194.676311, Pluto: 137.035122 },
  'sample-2000-sydney': { Sun: 340.279045, Moon: 276.398212, Mercury: 342.43298, Venus: 314.046658, Mars: 13.276395, Jupiter: 32.590853, Saturn: 42.371728, Uranus: 318.127001, Neptune: 305.352576, Pluto: 252.83849 },
  'sample-2024-london': { Sun: 84.856016, Moon: 188.518386, Mercury: 85.838489, Venus: 87.80716, Mars: 34.653729, Jupiter: 64.762331, Saturn: 349.257731, Uranus: 54.960273, Neptune: 359.853891, Pluto: 301.687938 },
  'sample-2060-southpole': { Sun: 84.321322, Moon: 269.891836, Mercury: 92.670763, Venus: 54.552978, Mars: 68.277282, Jupiter: 76.020547, Saturn: 69.172937, Uranus: 214.457747, Neptune: 78.519154, Pluto: 353.052632 },
  'sample-2100-shanghai': { Sun: 280.02353, Moon: 289.113209, Mercury: 297.824457, Venus: 265.398121, Mars: 253.769249, Jupiter: 226.950748, Saturn: 216.930341, Uranus: 21.731422, Neptune: 169.504313, Pluto: 33.381012 },
  'sample-1900-hongkong': { Sun: 359.859428, Moon: 230.751036, Mercury: 7.319465, Venus: 41.776923, Mars: 345.743382, Jupiter: 250.792978, Saturn: 274.551644, Uranus: 252.478131, Neptune: 84.27618, Pluto: 74.779206 },
  'sample-1920-hongkong': { Sun: 0.01087, Moon: 6.093131, Mercury: 358.8819, Venus: 332.798854, Mars: 218.887759, Jupiter: 128.419925, Saturn: 156.614993, Uranus: 333.252104, Neptune: 128.980951, Pluto: 95.67005 },
  'sample-1940-hongkong': { Sun: 0.159445, Moon: 139.382415, Mercury: 350.076918, Venus: 43.893815, Mars: 52.11693, Jupiter: 16.564375, Saturn: 30.061041, Uranus: 49.197685, Neptune: 173.979067, Pluto: 120.729244 },
  'sample-1960-hongkong': { Sun: 0.311951, Moon: 278.880344, Mercury: 342.678848, Venus: 335.971713, Mars: 320.491251, Jupiter: 272.217581, Saturn: 287.291317, Uranus: 137.439579, Neptune: 218.717817, Pluto: 154.275887 },
  'sample-1980-hongkong': { Sun: 0.458974, Moon: 57.921823, Mercury: 337.495893, Venus: 45.594638, Mars: 147.59004, Jupiter: 152.222638, Saturn: 173.109422, Uranus: 235.381972, Neptune: 262.671887, Pluto: 200.950839 },
  'sample-2000-hongkong': { Sun: 0.606565, Moon: 189.715875, Mercury: 334.479166, Venus: 339.195109, Mars: 28.431042, Jupiter: 36.731586, Saturn: 44.284287, Uranus: 319.171048, Neptune: 305.942651, Pluto: 252.893539 },
  'sample-2020-hongkong': { Sun: 0.762771, Moon: 322.83535, Mercury: 333.231275, Venus: 46.725825, Mars: 293.124096, Jupiter: 292.88164, Saturn: 299.906289, Uranus: 34.587689, Neptune: 348.863845, Pluto: 294.680662 },
  'sample-2040-hongkong': { Sun: 0.913079, Moon: 92.8364, Mercury: 333.303874, Venus: 342.470723, Mars: 101.237097, Jupiter: 176.403124, Saturn: 189.282749, Uranus: 119.41353, Neptune: 32.096375, Pluto: 326.214444 },
  'sample-2060-hongkong': { Sun: 1.059709, Moon: 221.918897, Mercury: 334.363886, Venus: 47.017343, Mars: 4.604043, Jupiter: 57.336252, Saturn: 59.002815, Uranus: 217.618364, Neptune: 75.955271, Pluto: 351.611086 },
  'sample-2080-hongkong': { Sun: 1.222013, Moon: 354.363736, Mercury: 336.191101, Venus: 345.784374, Mars: 258.634715, Jupiter: 313.035273, Saturn: 312.426864, Uranus: 304.756891, Neptune: 120.541921, Pluto: 13.374587 },
  'sample-2100-hongkong': { Sun: 0.379537, Moon: 111.897509, Mercury: 337.117424, Venus: 45.259759, Mars: 71.079643, Jupiter: 200.582936, Saturn: 205.024229, Uranus: 20.412308, Neptune: 165.568971, Pluto: 33.064288 },
};
